### ISSUE TITLE
Send out Lettuce Meet

### ISSUE THREAD

**Issue by ktjnyc** [hackla-engage/start-here#1]
### Overview
Figure out group meeting times

### Action Items
- [x] Send out lettuce meet to gather meeting times
- [x] Add everyone to issue 
- [x] Everyone fill out meeting times
- [x] Last one to fill out announces the meeting time 

### Resources/Instructions
[Lettuce meet](https://lettucemeet.com/l/Wnx7Y)

**Comment by eselkin** [comment]
Meeting time filled out (this is the one @BryonPm sent out, right?)

**Comment by ktjnyc** [comment]
Yes, that's it.  I think we just need @ExperimentsInHonesty to add her availability.

**Comment by BryonPm** [comment]
I wasn’t able to add Alex on that issue. His handle was not a part of the
list. He has included his availability on the site.

**Comment by eselkin** [comment]
I added Alex, he's participated on Google drive but not on github before, now he's on here.

**Comment by BryonPm** [comment]
@ExperimentsInHonesty On Wednesday night, the Engage Team agreed that Sunday at 4 p.m (PST) would be the best time slot for meeting. At your earliest convenience, please confirm.

**Comment by BryonPm** [comment]
Team decided on Sunday at 4PM to meet.
