### ISSUE TITLE
Create Engage Project Logo

### ISSUE THREAD

**Issue by ktjnyc** [hackla-engage/start-here#11]
### Overview
We need a new project logo so that we have a visual symbol of our product.

### Action Items

- [x] Create New Logo
- [x] Update [Issue 65](https://github.com/hackforla/product-management/issues/65) so that it goes back to review 
- [x] Update [Issue 36](https://github.com/hackforla/product-management/issues/36) so that the website can be updated
- [x] Add logo assets to  Google Drive folder
- [x] Add Logo to [One Sheet](https://docs.google.com/document/d/1Z8TZKnh4n9LNTe6WaEqb4rKI8cb3pMIEnVtabqSrMk8/edit?usp=sharing) 

### Resources/Instructions
[Logo Asset Goole Drive Folder](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en)

**Comment by ktjnyc** [comment]
@eselkin can you confirm Ryan has access to this repo?  I can't assign him to this issue - rmayott

**Comment by eselkin** [comment]
@ktjnyc Invited @rmayott

**Comment by rmayott** [comment]
@ktjnyc @eselkin I have access!

**Comment by BryonPm** [comment]
Met with Ryan on Saturday afternoon regarding logo direction. We discussed basic, rough concepts and inspiration. 
Next Steps:
Create Logo
- [ ] Create requirements document for logo reference and project value prop alignment.
- [x] Create initial design concepts.
- [x] Review initial concepts.
- [x] Iterate selected initial concept.

**Comment by rmayott** [comment]
Initial logo concepts complete.
![Engage Logo Concepts 01](https://user-images.githubusercontent.com/78511193/107204373-751e9b00-69b1-11eb-80dc-cedee20cfa94.jpg)

**Comment by ktjnyc** [comment]
@rmayott [One sheet](https://docs.google.com/document/d/1Z8TZKnh4n9LNTe6WaEqb4rKI8cb3pMIEnVtabqSrMk8/edit) is here

**Comment by rmayott** [comment]
Logo Iterations
![Engage Logo Iteration-01](https://user-images.githubusercontent.com/78511193/107871986-848f5f80-6e5b-11eb-9729-8adf2ba0ceaa.jpg)

**Comment by rmayott** [comment]
- Logo(.png & .svg) added to [Logo Folder](https://drive.google.com/drive/folders/1IKcfMf_Z4kqTrJPl3OB17jsEPgr8lrcm) in Google Drive
- Logo added to [One Sheet](https://docs.google.com/document/d/1Z8TZKnh4n9LNTe6WaEqb4rKI8cb3pMIEnVtabqSrMk8/edit)

**Comment by ktjnyc** [comment]
Added link to HfLA webiste update issue and moved One Sheet issue back to links/q's/review for.   Marked both complete above.
