### ISSUE TITLE
Logo usability study 

### ISSUE THREAD

**Issue by ktjnyc** [hackla-engage/start-here#15]
### Overview
We need to have a public vote on the potential logo. 

### Action Items
Text for usability study:
"Engage facilitates and streamlines preparation of meeting agendas, getting the word out to the local residents and compiling feedback from the public.  
Engage is a platform to help connect residents (and other stakeholders) to local government, instead of requiring constituents to be present at meetings." 

Bonnie's message:
@channel Please help us pick a logo for the Engage project.  

- [x] Create link
- [x] Send to Bonnie to send out

### Resources/Instructions
[Usability Hub](https://usabilityhub.com/)

**Comment by rmayott** [comment]
Logo Study created:
https://app.usabilityhub.com/do/f599bd2c3566/695e

**Comment by rmayott** [comment]
Sent to Bonnie

**Comment by rmayott** [comment]
Results
![screencapture-app-usabilityhub-tests-f599bd2c3566-results-2021-02-17-18_32_10](https://user-images.githubusercontent.com/78511193/108296676-d5020800-714e-11eb-9d38-5de4748ff685.png)

**Comment by BryonPm** [comment]
Decision was made to go with rounded logo.
