### ISSUE TITLE
Setup a slack reminder for our project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackla-engage/start-here#17]
### Overview
We need to create a reminder in the channel for people to update their issues, so that we can make the most of our meetings.

### Action Items
- [x] Read the guide to making a slack channel reminder
- [x] Draft a reminder message
- [x] Review with team

### Resources/Instructions
[Slack reminder guide WIP issue](https://github.com/hackforla/knowledgebase-content/issues/84)

**Comment by BryonPm** [comment]
Reminder was added to Slack.
