### ISSUE TITLE
Miro Account Creation

### ISSUE THREAD

**Issue by BryonPm** [hackla-engage/start-here#18]
### Overview
We need to create a Miro account for the Engage project.
### Action Items

- [x] Set up Engage Miro Account 

### Resources/Instructions
[https://github.com/hackforla/knowledgebase-content/issues/7](https://github.com/hackforla/knowledgebase-content/issues/7)

**Comment by rmayott** [comment]
Account created using engagehackforla@gmail.com account.
[Invitation link](https://miro.com/welcome/oJRTUm5LDfE6ktxZCccm9I9kbYrz4YLWrr9AVh1GY4TrPIH9QNqMyydw5namaTyi)
