### ISSUE TITLE
Review and Update One Sheet 

### ISSUE THREAD

**Issue by BryonPm** [hackla-engage/start-here#2]
### Overview
We need to review and update the one sheet so that we have alignment between organization, project, and stakeholders.
### Action Items
- [x] Locate existing one sheet
- [x] Review existing Wiki for backstory
- [x] Identify Google Drive 
    - [x] Confirm team access 
- [x] Refer to Wiki guide 
- [ ] Create new project logo
- [x] Review [civic tech structure one sheet](https://docs.google.com/document/d/1GkvbJ9byBWBpZklYE6YL5nqa-KbIRz32PnMCeroV_1g/edit)
- [x] Review [BOP project one sheet](https://docs.google.com/document/d/1P7HmROzkFYVyu7cFkzirwgO-F4i8v6ijQQ4PF44f5bE/edit)

### Resources/Instructions
[Previous Engage One Sheet](https://docs.google.com/document/d/18ICYthZPKQgtJnhV1PpMGUqIXeN7hAgRNC0E4JsIids/edit)
[Guide to drafting One Sheet](https://docs.google.com/document/d/14-nYNCjrMrC8lucUNBfLOFQZk2sWbkRlJgigWDAlqlI/edit?usp=sharing)
[Draft Engage One Sheet](https://docs.google.com/document/d/1Z8TZKnh4n9LNTe6WaEqb4rKI8cb3pMIEnVtabqSrMk8/edit?usp=sharing)
[General PM board issue](https://github.com/hackforla/product-management/issues/65)

**Comment by ktjnyc** [comment]
Progress: 
- Draft ready for review 
- Used logo from engage Github site - we mentioned creating new
- I've located the [google drive](https://drive.google.com/drive/folders/1rSrFjlzgJqJOIC4DMrANLj4tC0_ZJ3so?usp=sharing) but don't have access - we will need to update for this group
- Do we have a project email?

Blocks: 
- Used logo from engage Github site - we mentioned creating new
- I've located the [google drive](https://drive.google.com/drive/folders/1rSrFjlzgJqJOIC4DMrANLj4tC0_ZJ3so?usp=sharing) but don't have access - we will need to update for this group
- Do we have a project email?

Availability: pretty open this week
ETA: n/a

@BryonPm - could you take a look at the [draft ](https://docs.google.com/document/d/1Z8TZKnh4n9LNTe6WaEqb4rKI8cb3pMIEnVtabqSrMk8/edit?usp=sharing) I have put together and provide comments?

**Comment by eselkin** [comment]
@ktjnyc What's your email address to add you to the shared folder? You can message me in slack.

**Comment by BryonPm** [comment]
@ktjnyc Thanks for taking care of this! I will review and make comments by tomorrow.

**Comment by BryonPm** [comment]
@ktjnyc I reviewed the One Sheet and made a few comments. I think there are some opportunities areas for us to make progress on the Engage mission and make MVP identity clear.

**Comment by ktjnyc** [comment]
Thanks, @BryonPm I reviewed with Bonnie tonight and have a bunch of comments to incorporate.  Will send a new version once I've made the updates.

**Comment by ktjnyc** [comment]
Progress:
A good reminder regarding audience for this document - I've made some updates to reflect the council as the audience.  We can review the updated draft at the meeting tonight.  

Blocks:
Used logo from engage Github site - we mentioned creating new
Do we have a project email?

Availability: pretty open this week
ETA: n/a

**Comment by eselkin** [comment]
We have `engage@engage.town` I can give you the login credentials to that (not here and not in google drive)

**Comment by BryonPm** [comment]
@ktjnyc Thanks for the update! I planned on bringing that nuance up at the meeting. So, perfect. We will discuss tonight.  I believe clarity around our target will clear up any confusion regarding approach when we create other artifacts. Appreciate your professionalism.

**Comment by ktjnyc** [comment]
Notes from feedback discussion:

- [x] Update the Header line to include formal project name and website (refer to [VRMS one sheet](https://docs.google.com/document/d/1lsRUAAMs1b60LOqQb9H6c4Ky9AbQ7QN4FB1XNErKxEs/edit))
- [ ] Update top section to reflect inclusiveness and accessibility 
- [x]  Clarify the first bullet under history for reason why the library was chosen (demographics)
- [ ]  Additional items for history (get clarity from Eli) 
   - [x] created user personas 
   - [ ] built the software
   - [x] had people use it
   - [ ] compiled the comments into the pdfs 
   - [ ] delivered MVP of user comment interface

**Comment by ktjnyc** [comment]
Progress: Added notes from discussion with Bonnie to document and issue above.  
Blocks: None
Availability: pretty open this week
ETA: Can make next round of updates by Tuesday evening.

**Comment by ktjnyc** [comment]
Progress: Updated based upon notes from discussion with Bonnie. 
Blocks: 
- Need to discuss on team meeting updates and confirm pilot activities 
- Need to discuss project logo
- Need to discuss use of engage@engage.town for contact email 

Availability: pretty open this week
ETA: Can make next round of updates by Friday afternoon.
