### ISSUE TITLE
Archive old GitHub repositories

### ISSUE THREAD

**Issue by eselkin** [hackla-engage/start-here#3]
### Overview
Clean up the repositories. There are a few unsused cluttering repositories.

### Action Items
- [x] Determine which repos can be archived
- [x] Archive those not useful to future development

### Resources/Instructions
- GitHub

### Due by
1/27? next meeting

**Comment by hungrymonkey** [comment]
My bad for cluttering up the repository count since I have more issues attending meetings after the zoom transition. If you want me to archive my repos, I would not mind until I start actively developing them again.

**Comment by eselkin** [comment]
It's not just you, it was me too.

**Comment by eselkin** [comment]
Archived some of the not-currently-being-used/developed repositories.
